name: craftinomicon
description: Browsable recipe index
main: name.ball.joshua.craftinomicon.Craftinomicon
version: ${project.version}
author: sciolizer

permissions:
  craftinomicon.craft.book:
    description: Grants the ability to craft the craftinomicon.
    default: true
